# Generated by Django 4.1.1 on 2022-09-29 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('endereco', models.CharField(max_length=120)),
                ('born', models.DateField()),
                ('cpf', models.IntegerField()),
                ('nome_pai', models.CharField(max_length=120)),
                ('nome_mae', models.CharField(max_length=120)),
                ('sexo', models.CharField(max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(choices=[('C', 'casado'), ('S', 'solteiro')], max_length=120)),
                ('rg', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'CURSANDO'), ('A', 'APROVADO'), ('R', 'REPROVADO')], max_length=9)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='aluno', to='SIGAPI_rest.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('matriz_curricular', models.CharField(max_length=9)),
                ('data_vigor', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='insituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(unique=True)),
                ('born', models.DateField(verbose_name=str)),
                ('endereco', models.CharField(max_length=50)),
                ('salario', models.FloatField()),
                ('grau', models.CharField(choices=[('B', 'Bacharelado'), ('L', 'Licenciatura'), ('T', 'Tecnólogo')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PROFESSOR', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais_aluno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pai de aluno +', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('endereco', models.CharField(max_length=120)),
                ('born', models.DateField()),
                ('cpf', models.IntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=9)),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filho', to='SIGAPI_rest.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('isPresente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='FaltasDele', to='SIGAPI_rest.aluno')),
                ('botelim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boletim', to='SIGAPI_rest.boletim')),
            ],
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True)),
                ('endereco', models.CharField(max_length=120)),
                ('born', models.DateField()),
                ('cpf', models.IntegerField()),
                ('nome_pai', models.CharField(max_length=120)),
                ('nome_mae', models.CharField(max_length=120)),
                ('sexo', models.CharField(max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(choices=[('C', 'casado'), ('S', 'solteiro')], max_length=120)),
                ('rg', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresso', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtd_horas', models.PositiveIntegerField()),
                ('semestre', models.IntegerField()),
                ('pre_requisito', models.CharField(max_length=90)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor', to='SIGAPI_rest.professor')),
            ],
        ),
        migrations.AddField(
            model_name='boletim',
            name='disciplinas',
            field=models.ManyToManyField(to='SIGAPI_rest.disciplina'),
        ),
    ]
