# Generated by Django 4.1.1 on 2022-09-29 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIGAPI_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresso',
            name='id',
        ),
        migrations.AlterField(
            model_name='egresso',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Egresso', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
