# Generated by Django 4.1.1 on 2022-11-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIGAPI_rest', '0002_remove_egresso_id_alter_egresso_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais_aluno',
            name='filho',
        ),
        migrations.RemoveField(
            model_name='pais_aluno',
            name='user',
        ),
        migrations.DeleteModel(
            name='Egresso',
        ),
        migrations.DeleteModel(
            name='Pais_aluno',
        ),
    ]
